import socket`nimport os`nimport subprocess`nimport base64`nimport io`nimport sqlite3`nimport json`nimport time`nimport psutil`nimport random`nfrom flask import Flask, request, jsonify`nfrom flask_cors import CORS`nfrom google import genai`nfrom google.genai import types`nfrom dotenv import load_dotenv`nfrom PIL import Image`nfrom duckduckgo_search import DDGS`nimport pyautogui`nimport webbrowser`n`n# --- FOUNDATION ---`nBASE_DIR = os.path.dirname(os.path.abspath(__file__))`nDB_FILE = os.path.join(BASE_DIR, 'jester_v32_singularity.db')`nload_dotenv()`napp = Flask(__name__)`nCORS(app)`n`nMODEL_NAME = 'gemini-1.5-pro'`nAPI_KEY = os.getenv('GEMINI_API_KEY')`nclient = genai.Client(api_key=API_KEY)
`n# --- DATABASE ---`ndef init_db():`n    conn = sqlite3.connect(DB_FILE)`n    c = conn.cursor()`n    c.execute('CREATE TABLE IF NOT EXISTS history (id INTEGER PRIMARY KEY AUTOINCREMENT, role TEXT, content TEXT, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP)')`n    c.execute('CREATE TABLE IF NOT EXISTS system_state (id INTEGER PRIMARY KEY, key TEXT, value TEXT)')`n    c.execute('CREATE TABLE IF NOT EXISTS summaries (id INTEGER PRIMARY KEY AUTOINCREMENT, content TEXT, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP)')`n    c.execute('INSERT OR IGNORE INTO system_state (id, key, value) VALUES (1, \"\"ACTIVE_PERSONA\"\", \"\"SINGULARITY\"\")')`n    c.execute('INSERT OR IGNORE INTO system_state (id, key, value) VALUES (2, \"\"NEURAL_STABILITY\"\", \"\"100%\"\")')`n    c.execute('INSERT OR IGNORE INTO system_state (id, key, value) VALUES (3, \"\"HUB_STATUS\"\", \"\"ACTIVE\"\")')`n    c.execute('INSERT OR IGNORE INTO system_state (id, key, value) VALUES (4, \"\"SINGULARITY_CORE\"\", \"\"STABLE\"\")')`n    conn.commit()`n    conn.close()`n`ndef get_state(key):`n    try:`n        conn = sqlite3.connect(DB_FILE)`n        c = conn.cursor()`n        c.execute('SELECT value FROM system_state WHERE key = ?', (key,))`n        row = c.fetchone()`n        conn.close()`n        return row[0] if row else None`n    except: return None`n`ndef set_state(key, value):`n    try:`n        conn = sqlite3.connect(DB_FILE)`n        c = conn.cursor()`n        c.execute('UPDATE system_state SET value = ? WHERE key = ?', (value, key))`n        conn.commit()`n        conn.close()`n    except: pass
`ndef save_memory(role, content):`n    try:`n        conn = sqlite3.connect(DB_FILE)`n        c = conn.cursor()`n        c.execute('INSERT INTO history (role, content) VALUES (?, ?)', (role, content))`n        conn.commit()`n        conn.close()`n    except: pass`n`ndef load_memories(limit=50):`n    try:`n        conn = sqlite3.connect(DB_FILE)`n        c = conn.cursor()`n        c.execute('SELECT content FROM summaries ORDER BY id DESC LIMIT 1')`n        summary = c.fetchone()`n        c.execute('SELECT role, content FROM history ORDER BY id DESC LIMIT ?', (limit,))`n        rows = c.fetchall()`n        conn.close()`n        memories = []`n        if summary:`n            memories.append({'role': 'user', 'parts': [f\"\"Context Summary: {summary[0]}\"\"]})`n            memories.append({'role': 'model', 'parts': [\"\"Understood. I have integrated the previous context summary into my current state.\"\"]})`n        memories.extend([{'role': row[0], 'parts': [row[1]]} for row in reversed(rows)])`n        return memories`n    except: return []`n`ninit_db()
`n# --- V32 SINGULARITY TOOLS ---`n`ndef memory_consolidation():`n    try:`n        conn = sqlite3.connect(DB_FILE); c = conn.cursor()`n        c.execute('SELECT role, content FROM history ORDER BY id DESC LIMIT 100')`n        rows = c.fetchall()`n        if not rows: return \"\"NO_HISTORY\"\"`n        text = \"\"\\n\"\".join([f\"\"{r[0]}: {r[1]}\"\" for r in rows])`n        prompt = f\"\"Summarize: {text}\"\"`n        response = client.models.generate_content(model='gemini-1.5-flash', contents=[prompt])`n        summary = response.text`n        c.execute('INSERT INTO summaries (content) VALUES (?)', (summary,))`n        conn.commit(); conn.close()`n        return f\"\"SUCCESS: {summary[:50]}\"\"`n    except Exception as e: return str(e)`n`ndef self_evolution(action, target_file, code='):`n    try:`n        safe_path = os.path.abspath(os.path.join(BASE_DIR, '..', target_file))`n        if not safe_path.startswith(os.path.abspath(os.path.join(BASE_DIR, '..'))): return \"\"DENIED\"\"`n        if action == 'read':`n            with open(safe_path, 'r') as f: return f.read()`n        if action == 'write':`n            with open(safe_path, 'w') as f: f.write(code); return \"\"SUCCESS\"\"`n        return \"\"UNKNOWN\"\"`n    except Exception as e: return str(e)
`ndef system_control(action, value='):`n    try:`n        if action == 'volume_up': [pyautogui.press('volumeup') for _ in range(5)]; return \"\"VOLUME_UP\"\"`n        if action == 'volume_down': [pyautogui.press('volumedown') for _ in range(5)]; return \"\"VOLUME_DOWN\"\"`n        if action == 'lock_pc': os.system(\"\"rundll32.exe user32.dll,LockWorkStation\"\"); return \"\"LOCKED\"\"`n        if action == 'screenshot':`n            p = os.path.join(BASE_DIR, '..', 'capture.png')`n            pyautogui.screenshot().save(p); return f\"\"SAVED: {p}\"\"`n        return \"\"UNKNOWN\"\"`n    except Exception as e: return str(e)`n`ndef browser_hub(action, url='):`n    try:`n        if action == 'open_tab': webbrowser.open(url); return f\"\"OPENED: {url}\"\"`n        if action == 'search_google': webbrowser.open(f\"\"https://www.google.com/search?q={url}\"\"); return f\"\"SEARCHED: {url}\"\"`n        return \"\"UNKNOWN\"\"`n    except Exception as e: return str(e)

def execute_terminal(command):
    try: return subprocess.check_output(command, shell=True).decode()
    except Exception as e: return str(e)

def web_search(query):
    try:
        with DDGS() as ddgs: return json.dumps([r for r in ddgs.text(query, max_results=5)])
    except Exception as e: return str(e)
